networks:
  demo:
    driver: bridge
   
volumes:
  n8n_storage:
  postgres_storage:
  ollama_storage:
  qdrant_storage:
  open-webui:
  flowise:
  text-generation-webui:
  localai_models:
  localai_images:
  vllm_cache:
  neo4j_data:
  neo4j_logs:
  
x-n8n: &service-n8n
  image: n8nio/n8n:latest
  networks: ['demo']
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_USER=postgres
    - DB_POSTGRESDB_PASSWORD=password123
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_ENCRYPTION_KEY=Thatsapp!esn0ranges
    - N8N_USER_MANAGEMENT_JWT_SECRET=Rump!e&Hobbes
  links:
    - postgres

x-ollama: &service-ollama
  image: ollama/ollama:latest
  container_name: ollama
  networks: ['demo']
  restart: unless-stopped
  ports:
    - 11434:11434
  volumes:
    - ollama_storage:/root/.ollama

x-init-ollama: &init-ollama
  image: ollama/ollama:latest
  networks: ['demo']
  container_name: ollama-pull-llama
  volumes:
    - ollama_storage:/root/.ollama
  entrypoint: /bin/sh
  command:
    - "-c"
    - "sleep 3; OLLAMA_HOST=ollama:11434 ollama pull llama3.2; OLLAMA_HOST=ollama:11434 ollama pull nomic-embed-text"

services:
  flowise:
    image: flowiseai/flowise
    networks: ['demo']
    restart: unless-stopped
    container_name: flowise
    environment:
        - PORT=3001
    ports:
        - 3001:3001
    extra_hosts:
      - "host.docker.internal:host-gateway"        
    volumes:
        - flowise:/root/.flowise
    entrypoint: /bin/sh -c "sleep 3; flowise start"

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    networks: ['demo']
    restart: unless-stopped
    container_name: open-webui
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui:/app/backend/data

  postgres:
    image: postgres:16-alpine
    networks: ['demo']
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: n8n
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U postgres -d n8n']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n-import:
    <<: *service-n8n
    container_name: n8n-import
    entrypoint: /bin/sh
    command:
      - "-c"
      - "n8n import:credentials --separate --input=/backup/credentials && n8n import:workflow --separate --input=/backup/workflows"
    volumes:
      - ./n8n/backup:/backup
    depends_on:
      postgres:
        condition: service_healthy

  n8n:
    <<: *service-n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - 5678:5678
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./n8n/backup:/backup
      - ./shared:/data/shared
    depends_on:
      postgres:
        condition: service_healthy

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    networks: ['demo']
    restart: unless-stopped
    ports:
      - 6333:6333
    volumes:
      - qdrant_storage:/qdrant/storage

  # Neo4j Graph Database
  neo4j:
    image: neo4j:5-community
    container_name: neo4j
    networks: ['demo']
    restart: unless-stopped
    ports:
      - 7474:7474  # HTTP
      - 7687:7687  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]

  # Text Generation WebUI - GPU version
  text-generation-webui:
    profiles: ["gpu-nvidia"]
    image: atinoda/text-generation-webui:default-nvidia
    container_name: text-generation-webui
    networks: ['demo']
    restart: unless-stopped
    ports:
      - 7860:7860
      - 5000:5000  # API port
      - 5005:5005  # Streaming API port
    volumes:
      - text-generation-webui:/app/text-generation-webui
      - ./models:/app/text-generation-webui/models
      - ./loras:/app/text-generation-webui/loras
      - ./characters:/app/text-generation-webui/characters
    environment:
      - CLI_ARGS=--listen --api --extensions openai
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # LocalAI - GPU version
  localai:
    profiles: ["gpu-nvidia"]
    image: localai/localai:latest-aio-gpu-nvidia-cuda-12
    container_name: localai
    networks: ['demo']
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - localai_models:/build/models
      - localai_images:/tmp/generated/images
    environment:
      - THREADS=8
      - CONTEXT_SIZE=4096
      - DEBUG=false
      - GALLERIES=[{"name":"model-gallery","url":"github:go-skynet/model-gallery/index.yaml"}]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # vLLM - GPU version
  vllm:
    profiles: ["gpu-nvidia"]
    image: vllm/vllm-openai:latest
    container_name: vllm
    networks: ['demo']
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - vllm_cache:/root/.cache/vllm
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN:-}
    # Note: You'll need to specify a model when starting
    # Example command override:
    # command: --model mistralai/Mistral-7B-Instruct-v0.2 --gpu-memory-utilization 0.95
    entrypoint: python -m vllm.entrypoints.openai.api_server
    command: --host 0.0.0.0 --model facebook/opt-125m  # Default small model, change this
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: '16gb'  # Important for vLLM performance

  # CPU versions (optional)
  text-generation-webui-cpu:
    profiles: ["cpu"]
    image: atinoda/text-generation-webui:default
    container_name: text-generation-webui-cpu
    networks: ['demo']
    restart: unless-stopped
    ports:
      - 7860:7860
      - 5000:5000
      - 5005:5005
    volumes:
      - text-generation-webui:/app/text-generation-webui
      - ./models:/app/text-generation-webui/models
    environment:
      - CLI_ARGS=--listen --api --cpu

  localai-cpu:
    profiles: ["cpu"]
    image: localai/localai:latest-aio-cpu
    container_name: localai-cpu
    networks: ['demo']
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - localai_models:/build/models
      - localai_images:/tmp/generated/images
    environment:
      - THREADS=8
      - CONTEXT_SIZE=4096

  ollama-cpu:
    profiles: ["cpu"]
    <<: *service-ollama

  ollama-gpu:
    profiles: ["gpu-nvidia"]
    <<: *service-ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama-pull-llama-cpu:
    profiles: ["cpu"]
    <<: *init-ollama
    depends_on:
      - ollama-cpu

  ollama-pull-llama-gpu:
    profiles: ["gpu-nvidia"]
    <<: *init-ollama
    depends_on:
      - ollama-gpu