# Additional RevitAI services
# Use with: docker-compose -f docker-compose.yml -f docker-compose.revitai.yml up -d

services:
  # n8n worker for distributed processing
  n8n-worker:
    image: n8nio/n8n:latest
    networks: ['demo']
    container_name: n8n-worker
    restart: unless-stopped
    ports:
      - 5679:5678
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=password123
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_ENCRYPTION_KEY=Thatsapp!esn0ranges
      - N8N_USER_MANAGEMENT_JWT_SECRET=Rump!e&Hobbes
      - NODE_ID=worker1
      - MAIN_NODE_URL=http://n8n:5678
    depends_on:
      - postgres
      - n8n

  # MCP Mock Server (for development)
  mcp-server:
    image: python:3.11-slim
    container_name: mcp-server
    networks: ['demo']
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./mcp-server:/app
    working_dir: /app
    command: >
      sh -c "pip install fastapi uvicorn &&
             python -m uvicorn server:app --host 0.0.0.0 --port 8080"
